lib/kombuchi_server_web/router.ex
defmodule KombuchiServerWeb.Router do
  use KombuchiServerWeb, :router

  import KombuchiServerWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KombuchiServerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KombuchiServerWeb do
    pipe_through :browser

    # get "/", PageController, :index

    live_session :user do

      live "/", SubscribeLive.Front, :index
      live "/user_register", SubscribeLive.Front, :user_register
    end

    live "/sellers", SellerLive.Index, :index
    live "/sellers/new", SellerLive.Index, :new
    live "/sellers/:id/edit", SellerLive.Index, :edit

    live "/sellers/:id", SellerLive.Show, :show
    live "/sellers/:id/show/edit", SellerLive.Show, :edit


    live "/subscribers", SubscribeLive.Index, :index
    live "/subscribers/new", SubscribeLive.Index, :new
    live "/subscribers/:id/edit", SubscribeLive.Index, :edit

    live "/subscribers/:id", SubscribeLive.Show, :show
    live "/subscribers/:id/show/edit", SubscribeLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", KombuchiServerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: KombuchiServerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes


  # requires unauthenticated scope
  scope "/", KombuchiServerWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  # authenticated scope
  scope "/", KombuchiServerWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/profile", UserSettingsController, :profile
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  # public scope
  scope "/", KombuchiServerWeb do
    pipe_through [:browser]


    live "/sell_items", SellItemLive.Index, :index
    live "/sell_items/new", SellItemLive.Index, :new
    live "/sell_items/:id/edit", SellItemLive.Index, :edit

    live "/sell_items/:id", SellItemLive.Show, :show
    live "/sell_items/:id/show/edit", SellItemLive.Show, :edit


    # TODO add /sale_points
    get "/sell_points", PageController, :sell_points
    get "/users/log_out", UserSessionController, :delete
    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    put "/users/confirm/:token", UserConfirmationController, :update
    post "/users/confirm/:token", UserConfirmationController, :update
  end


  scope "/api/swagger" do
    forward "/", PhoenixSwagger.Plug.SwaggerUI, otp_app: :kombuchi_server, swagger_file: "swagger.json"
  end

  def swagger_info do
    %{
      info: %{
        version: "1.0",
        title: "My App"
      }
    }
  end

end

lib/kombuchi_server_web/controllers/user_session_controller.ex
defmodule KombuchiServerWeb.UserSessionController do
  use KombuchiServerWeb, :controller

  alias KombuchiServer.Accounts
  alias KombuchiServerWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/kombuchi_server_web/views/user_session_view.ex
defmodule KombuchiServerWeb.UserSessionView do
  use KombuchiServerWeb, :view
end

lib/kombuchi_server_web/templates/user_session/_social_media_login.html.heex
<div>
    <ul class="grid grid-cols-3 gap-4">
      <li class="button-secondary">
        <img class="h-8" src={ Routes.static_path(@conn, "/images/social-google.svg") } />
      </li>
      <li class="button-secondary">
        <img class="h-8" src={ Routes.static_path(@conn, "/images/social-facebook.svg") } />
      </li>
      <li class="button-secondary">
        <img class="h-8" src={ Routes.static_path(@conn, "/images/social-twitter.svg") } />
      </li>
    </ul>
  </div>

lib/kombuchi_server_web/templates/user_session/new.html.heex
<div class="md:h-3/6 lg:h-4/6">

  <div class="flex max-w-sm h-auto mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 md:my-12 lg:max-w-4xl">
    <div class="hidden bg-cover lg:block lg:w-1/2" style="background-image:url('https://images.unsplash.com/photo-1606660265514-358ebbadc80d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1575&q=80')"></div>
    
    <div class="w-full px-6 py-8 md:px-8 lg:w-1/2">
      <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
        <div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <div class="max-w-md w-full space-y-8">
            <form class="mt-8 space-y-6" action="#" method="POST">
              <input type="hidden" name="remember" value="true">
              <div class="rounded-md shadow-sm -space-y-px">
                <div>
                  <label for="email-address" class="sr-only">Email address</label>
                  <%= email_input f, :email, required: true, placeholder: "Correo electronico", class: "common-input" %>
                </div>
                <div class="pt-2">
                  <label for="password" class="sr-only">Password</label>
                  <%= password_input f, :password, required: true, placeholder: "Password", class: "common-input" %>
                </div>
              </div>
              <%= if @error_message do %>
              <div class="alert alert-danger ">
                <p><%= @error_message %></p>
              </div>
              <% end %>    
              <div>
                <button type="submit" class="button-primary group">
                  <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                    <!-- Heroicon name: solid/lock-closed -->
                    <svg class="h-5 w-5 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                    </svg>
                  </span>
                  Entrar
                </button>
              </div>
              
              <!--div class="relative flex items-center">
                <div class="flex-grow border-t border-gray-200"></div>
                <span class="flex-shrink mx-4 text-sm text-gray-400">Continua con</span>
                <div class="flex-grow border-t border-gray-200"></div>
              </div-->

              <%# render "_social_media_login.html", conn: @conn %>
              <div class="flex items-center justify-between">
                <div class="common-form-anchor">
                  <a href="#" class=""> 
                    <%= link "Olvidaste tu contraseña?", to: Routes.user_reset_password_path(@conn, :new) %>
                  </a>
                </div>
                <div class="common-form-anchor">
                  <a href="#" class=""> <%= link "Registrate", to: Routes.user_registration_path(@conn, :new) %> </a>
                </div>
              </div>
              
            </form>
          </div>
        </div>
        
      </.form>
    </div>
    
  </div>
  
</div>